import { Resource, select, excerpt, NOTION_TABS, inNotionTab } from './model';
import { PortalData, PortalActions } from './portal';
import { BudgetReport, currency } from './budget';
export interface BudgetSource {path:string;report?:BudgetReport;error?:string}
export class Tabbed {
 private main!:HTMLElement;private nav!:HTMLElement;private status!:HTMLElement;private query='';private active='Content';private page=0;
 constructor(private host:HTMLElement,private data:PortalData,private actions:PortalActions,private budgets:BudgetSource[]=[]){this.shell();}
 update(data:PortalData,budgets:BudgetSource[]){this.data=data;this.budgets=budgets;this.tabs();this.render();}
 private btn(parent:HTMLElement,label:string,action:()=>unknown,cls=''){const b=parent.createEl('button',{text:label,cls,attr:{type:'button'}});b.onclick=()=>{try{Promise.resolve(action()).catch(this.actions.error);}catch(e){this.actions.error(e);}};return b;}
 private shell(){const crumbs=this.host.createDiv({cls:'uud-notion-crumb',text:this.data.folder.replaceAll('/',' / ')});
  const header=this.host.createEl('header',{cls:'uud-notion-header'});header.createDiv({cls:'uud-notion-icon',text:this.data.config.template==='budget'?'▤':'▦'});header.createEl('h1',{text:this.data.title});if(this.data.description)header.createEl('p',{text:this.data.description});
  const controls=this.host.createDiv('uud-notion-controls');this.btn(controls,'New note',this.actions.newNote);this.btn(controls,'Settings',this.actions.settings);this.btn(controls,'Refresh',this.actions.refresh);this.btn(controls,'Talk to dashboard',this.actions.talk);
  const label=controls.createEl('label',{text:'Search documents '});const input=label.createEl('input',{type:'search',attr:{'aria-label':'Search document contents',placeholder:'Search inside notes and PDFs…'}});input.oninput=()=>{this.query=input.value;this.page=0;this.render();};
  this.status=this.host.createDiv({cls:'uud-content-status',attr:{role:'status'}});
  this.nav=this.host.createDiv({cls:'uud-notion-tabs',attr:{role:'tablist','aria-label':'Dashboard views'}});this.main=this.host.createDiv({cls:'uud-notion-panel',attr:{role:'tabpanel',id:'uud-panel-'+Math.random().toString(36).slice(2)}});this.tabs();this.render();
 }
 private tabs(){const labels=this.data.config.template==='budget'?['Overview',...this.budgets.map(b=>b.path)]:[...NOTION_TABS];if(!labels.includes(this.active))this.active=labels[0];this.nav.empty();
  for(const value of labels){const source=this.budgets.find(b=>b.path===value);const label=source?(source.report?.title.split(' Budgets')[0]||value.split('/').at(-1)!.replace(/\.pdf$/i,'')):value;const b=this.btn(this.nav,label,()=>{this.active=value;this.page=0;this.tabs();this.render();});b.setAttribute('role','tab');b.setAttribute('aria-selected',String(value===this.active));b.setAttribute('aria-controls',this.main.id);b.tabIndex=value===this.active?0:-1;b.onkeydown=e=>{const idx=labels.indexOf(value);let next=idx;if(e.key==='ArrowRight')next=(idx+1)%labels.length;else if(e.key==='ArrowLeft')next=(idx+labels.length-1)%labels.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=labels.length-1;else return;e.preventDefault();this.active=labels[next];this.tabs();this.render();(this.nav.children[next] as HTMLElement).focus();};}
 }
 private render(){this.main.empty();this.status.setText(this.data.items.some(r=>r.content===undefined)?'Reading document contents…':`${this.data.items.length} resources · Search includes notes, PDFs, and embedded documents`);
  const failed=this.data.items.filter(r=>r.contentError);if(failed.length)this.main.createEl('p',{cls:'uud-import-warning',text:`Text unavailable or incomplete for ${failed.length} resource(s): ${failed.map(r=>r.title+': '+r.contentError).join('; ')}`});
  if(this.data.config.template==='budget'){this.renderBudgets();return;}
  if(this.active==='Folders'){if(!this.data.folders.length)this.main.createEl('p',{text:'No subfolders yet.'});for(const f of this.data.folders)this.btn(this.main,'▱ '+f.name,()=>this.actions.openFolder(f.path),'uud-notion-folder');return;}
  const items=select(this.data.items,this.query,this.data.config.filters,this.data.config.sort).filter(r=>inNotionTab(r,this.active,this.data.folder));
  this.main.createEl('p',{cls:'uud-muted',text:`${items.length} ${this.active.toLowerCase()} resource${items.length===1?'':'s'}`});if(!items.length){this.main.createEl('p',{text:'No matching resources. Try another tab or search.'});return;}
  const wrap=this.main.createDiv('uud-table-scroll');const table=wrap.createEl('table',{cls:'uud-notion-table'});const tr=table.createEl('thead').createEl('tr');for(const label of ['Name','Type','Status','Updated','Actions'])tr.createEl('th',{text:label,attr:{scope:'col'}});
  const body=table.createEl('tbody');const size=this.data.pageSize;this.page=Math.min(this.page,Math.max(0,Math.ceil(items.length/size)-1));for(const r of items.slice(this.page*size,(this.page+1)*size)){const row=body.createEl('tr');const name=row.createEl('td');this.btn(name,'▧ '+r.title,()=>this.actions.open(r),'uud-notion-title');const match=excerpt(r,this.query);if(match)name.createEl('p',{cls:'uud-match',text:match});row.createEl('td',{text:r.type.join(', ')});const status=row.createEl('td');for(const s of r.status)status.createSpan({cls:'uud-notion-badge',text:s});row.createEl('td',{text:new Date(r.mtime).toLocaleDateString()});const b=this.btn(row.createEl('td'),'•••',()=>this.actions.menu(b,r));b.setAttribute('aria-label','Actions for '+r.title);}
  if(items.length>size){const pager=this.main.createDiv('uud-pagination');this.btn(pager,'Previous',()=>{this.page--;this.render();}).disabled=this.page===0;pager.createSpan({text:`Page ${this.page+1} of ${Math.ceil(items.length/size)}`});this.btn(pager,'Next',()=>{this.page++;this.render();}).disabled=(this.page+1)*size>=items.length;}
 }
 private table(parent:HTMLElement,labels:string[],rows:{label?:string[];values:number[];total?:boolean}[]){const wrap=parent.createDiv('uud-table-scroll');wrap.tabIndex=0;wrap.setAttribute('aria-label','Budget table, scroll horizontally for more columns');const table=wrap.createEl('table',{cls:'uud-budget-table'});const head=table.createEl('thead').createEl('tr');for(const text of labels)head.createEl('th',{text,attr:{scope:'col'}});const body=table.createEl('tbody');for(const row of rows){const tr=body.createEl('tr',{cls:row.total?'uud-budget-total':''});for(const text of row.label||[])tr.createEl('td',{text,cls:'uud-budget-label'});row.values.forEach((n,i)=>tr.createEl('td',{text:currency(n),cls:i===row.values.length-1?(n<0?'uud-negative':'uud-positive'):''}));}}
 private renderBudgets(){
  if(!this.budgets.length){this.main.createEl('p',{text:'Add a Remaining by Line Item PDF to this folder to display its budget.'});return;}
  const sources=this.active==='Overview'?this.budgets:this.budgets.filter(b=>b.path===this.active);
  for(const source of sources){const report=source.report;const section=this.main.createEl('section',{cls:'uud-budget-report'});const resource=this.data.items.find(r=>r.path===source.path);section.createEl('h2',{text:report?.title||resource?.title||'Budget PDF'});if(resource)this.btn(section,'Open source PDF ↗',()=>this.actions.open(resource),'uud-source-link');if(source.error)section.createEl('p',{cls:'uud-import-warning',text:source.error});if(!report){section.createEl('p',{text:source.error?'Text could not be imported. Use the source PDF.':'Reading budget PDF…'});continue;}
   section.createEl('p',{text:report.subtitle});section.createEl('p',{cls:'uud-muted',text:report.note});for(const warning of report.warnings)section.createEl('p',{cls:'uud-import-warning',text:warning});
   if(report.rollup.length===7){section.createEl('h3',{text:`Collective rollup (${report.funds.length} fund${report.funds.length===1?'':'s'})`});this.table(section,['Original','Adjustments','Adj Budget','Req','PO (Enc)','Actuals','Remaining'],[{values:report.rollup,total:true}]);}
   for(const note of report.notes)section.createEl('p',{cls:'uud-budget-note',text:note});
   if(this.active==='Overview'&&!this.query.trim())continue;
   let count=0;for(const fund of report.funds){const words=this.query.toLowerCase().trim().split(/\s+/).filter(Boolean);const rows=fund.rows.filter(r=>words.every(w=>`${fund.title} ${r.object} ${r.label} ${r.values.map(currency).join(' ')}`.toLowerCase().includes(w)));if(!rows.length)continue;count+=rows.length;section.createEl('h3',{text:fund.title});section.createEl('p',{cls:'uud-muted',text:`Source page ${fund.page}${this.query?' · Filtered line items; fund total includes all rows':''}`});this.table(section,['Obj','Line item','Original','Adj Δ','Adj Budget','PO (Enc)','Actuals','Remaining'],[...rows.map(r=>({label:[r.object,r.label],values:r.values})),...(fund.total.length===6?[{label:['','FUND TOTAL'],values:fund.total,total:true}]:[])]);}
   if(!count)section.createEl('p',{text:'No matching budget line items.'});
  }
 }
}
